import time
import random
import sys
time.sleep(0.01)
print("请输入大于等于5的字符串，否则程序会出错")
x = input()
print("正在对",x,"进行检查")
print("正在检查大小写（中文和数字可不在意）")
time.sleep(4)
print(x.upper())
time.sleep(1)
print(x.lower())
time.sleep(1)
print("字符串长度:", len(x))
time.sleep(1)
print("正在对前5个字符检查")
print(x[0])
time.sleep(1)
print(x[1])
time.sleep(1)
print(x[2])
print(x[3])
time.sleep(1)
print(x[4])
print("正在检查数据类型")
time.sleep(3)
print(type(x))
time.sleep(1)
print("正在计算错误数量……")
print("预计5秒")
time.sleep(5)
print("错误数：")
time.sleep(0.2)
print(random.randrange(0,345))
print("正在为您修复……")
time.sleep(1)
print("正在为您删除开头和结尾的空白字符")
print(x.strip())
print("正在修复其余问题")
time.sleep(random.randrange(6,20))
print("无法修复，正在为您退出程序")
time.sleep(5)
sys.exit(886)
